if (NOT DEFINED DX12_RENDERER_SOURCE_ROOT OR NOT DEFINED DX12_RENDERER_OIDN_BUILD_DIRECTORY OR NOT DEFINED DX12_RENDERER_CONFIGURATION)
        message(FATAL_ERROR "The OIDN build script requires source, build, and configuration arguments.")
endif()

set(DX12_RENDERER_OIDN_SOURCE_DIRECTORY "${DX12_RENDERER_SOURCE_ROOT}/External/OIDN")
set(DX12_RENDERER_OIDN_OUTPUT_DIRECTORY "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/${DX12_RENDERER_CONFIGURATION}")
set(DX12_RENDERER_OIDN_OUTPUTS
        "${DX12_RENDERER_OIDN_OUTPUT_DIRECTORY}/OpenImageDenoise.lib"
        "${DX12_RENDERER_OIDN_OUTPUT_DIRECTORY}/OpenImageDenoise.dll"
        "${DX12_RENDERER_OIDN_OUTPUT_DIRECTORY}/OpenImageDenoise_core.dll"
        "${DX12_RENDERER_OIDN_OUTPUT_DIRECTORY}/OpenImageDenoise_device_cpu.dll"
        "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/include/OpenImageDenoise/config.h"
        )
set(DX12_RENDERER_OIDN_STAMP "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/oidn_${DX12_RENDERER_CONFIGURATION}.stamp")
set(DX12_RENDERER_OIDN_INPUTS
        "${DX12_RENDERER_SOURCE_ROOT}/CMakeIncludes/BuildOidn.cmake"
        "${DX12_RENDERER_SOURCE_ROOT}/CMakeIncludes/ThirdPartyDependencies.cmake"
        "${DX12_RENDERER_OIDN_SOURCE_DIRECTORY}/CMakeLists.txt"
        "${DX12_RENDERER_OIDN_SOURCE_DIRECTORY}/api/CMakeLists.txt"
        "${DX12_RENDERER_OIDN_SOURCE_DIRECTORY}/core/CMakeLists.txt"
        "${DX12_RENDERER_OIDN_SOURCE_DIRECTORY}/devices/cpu/CMakeLists.txt"
        "${DX12_RENDERER_OIDN_SOURCE_DIRECTORY}/cmake/oidn_common.cmake"
        "${DX12_RENDERER_OIDN_SOURCE_DIRECTORY}/cmake/oidn_ispc.cmake"
        )

if (NOT EXISTS "${DX12_RENDERER_OIDN_SOURCE_DIRECTORY}/include/OpenImageDenoise/oidn.hpp")
        message(FATAL_ERROR "OIDN submodule is not initialized. Run git submodule update --init --recursive.")
endif()
if (NOT EXISTS "${DX12_RENDERER_OIDN_ISPC_EXECUTABLE}")
        message(FATAL_ERROR "OIDN requires ISPC 1.30.0 at ${DX12_RENDERER_OIDN_ISPC_EXECUTABLE}.")
endif()
if (NOT EXISTS "${DX12_RENDERER_OIDN_TBB_CONFIG_DIRECTORY}/TBBConfig.cmake")
        message(FATAL_ERROR "OIDN requires oneTBB at ${DX12_RENDERER_OIDN_TBB_ROOT}. Install tbb:x64-windows with vcpkg.")
endif()

set(DX12_RENDERER_OIDN_REBUILD_REQUIRED FALSE)
if (NOT EXISTS "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/CMakeCache.txt" OR NOT EXISTS "${DX12_RENDERER_OIDN_STAMP}")
        set(DX12_RENDERER_OIDN_REBUILD_REQUIRED TRUE)
endif()
foreach(DX12_RENDERER_OIDN_OUTPUT IN LISTS DX12_RENDERER_OIDN_OUTPUTS)
        if (NOT EXISTS "${DX12_RENDERER_OIDN_OUTPUT}")
                set(DX12_RENDERER_OIDN_REBUILD_REQUIRED TRUE)
                break()
        endif()
endforeach()
foreach(DX12_RENDERER_OIDN_INPUT IN LISTS DX12_RENDERER_OIDN_INPUTS)
        if ("${DX12_RENDERER_OIDN_INPUT}" IS_NEWER_THAN "${DX12_RENDERER_OIDN_STAMP}")
                set(DX12_RENDERER_OIDN_REBUILD_REQUIRED TRUE)
                break()
        endif()
endforeach()

if (NOT DX12_RENDERER_OIDN_REBUILD_REQUIRED)
        message(STATUS "OIDN CPU artifacts are up to date.")
        return()
endif()

set(DX12_RENDERER_OIDN_CONFIGURE_COMMAND
        "${CMAKE_COMMAND}"
        -S "${DX12_RENDERER_OIDN_SOURCE_DIRECTORY}"
        -B "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}"
        -G "${DX12_RENDERER_GENERATOR}"
        "-DCMAKE_BUILD_TYPE=${DX12_RENDERER_CONFIGURATION}"
        "-DOIDN_APPS=OFF"
        "-DOIDN_DEVICE_CPU=ON"
        "-DOIDN_DEVICE_SYCL=OFF"
        "-DOIDN_DEVICE_CUDA=OFF"
        "-DOIDN_DEVICE_HIP=OFF"
        "-DOIDN_FILTER_RT=ON"
        "-DOIDN_FILTER_RTLIGHTMAP=OFF"
        "-DOIDN_LIBRARY_VERSIONED=OFF"
        "-DOIDN_INSTALL_DEPENDENCIES=OFF"
        "-DISPC_EXECUTABLE=${DX12_RENDERER_OIDN_ISPC_EXECUTABLE}"
        "-DTBB_ROOT=${DX12_RENDERER_OIDN_TBB_ROOT}"
        "-DTBB_DIR=${DX12_RENDERER_OIDN_TBB_CONFIG_DIRECTORY}"
        )
if (DX12_RENDERER_GENERATOR_PLATFORM)
        list(APPEND DX12_RENDERER_OIDN_CONFIGURE_COMMAND -A "${DX12_RENDERER_GENERATOR_PLATFORM}")
endif()
if (DX12_RENDERER_GENERATOR_TOOLSET)
        list(APPEND DX12_RENDERER_OIDN_CONFIGURE_COMMAND -T "${DX12_RENDERER_GENERATOR_TOOLSET}")
endif()
if (DX12_RENDERER_TOOLCHAIN_FILE)
        list(APPEND DX12_RENDERER_OIDN_CONFIGURE_COMMAND "-DCMAKE_TOOLCHAIN_FILE=${DX12_RENDERER_TOOLCHAIN_FILE}")
endif()

message(STATUS "Building isolated Open Image Denoise CPU dependency")
execute_process(COMMAND ${DX12_RENDERER_OIDN_CONFIGURE_COMMAND} RESULT_VARIABLE DX12_RENDERER_OIDN_CONFIGURE_RESULT)
if (NOT DX12_RENDERER_OIDN_CONFIGURE_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to configure isolated Open Image Denoise dependency.")
endif()

execute_process(
        COMMAND "${CMAKE_COMMAND}" --build "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}" --config "${DX12_RENDERER_CONFIGURATION}" --target OpenImageDenoise OpenImageDenoise_device_cpu
        RESULT_VARIABLE DX12_RENDERER_OIDN_BUILD_RESULT)
if (NOT DX12_RENDERER_OIDN_BUILD_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to build isolated Open Image Denoise dependency.")
endif()
foreach(DX12_RENDERER_OIDN_OUTPUT IN LISTS DX12_RENDERER_OIDN_OUTPUTS)
        if (NOT EXISTS "${DX12_RENDERER_OIDN_OUTPUT}")
                message(FATAL_ERROR "OIDN build did not produce ${DX12_RENDERER_OIDN_OUTPUT}.")
        endif()
endforeach()
file(TOUCH "${DX12_RENDERER_OIDN_STAMP}")
