if (NOT DEFINED DX12_RENDERER_SOURCE_ROOT OR NOT DEFINED DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY OR NOT DEFINED DX12_RENDERER_CONFIGURATION)
        message(FATAL_ERROR "The renderer third-party build script requires source, build, and configuration arguments.")
endif()

set(DX12_RENDERER_THIRD_PARTY_OUTPUT_DIRECTORY "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/${DX12_RENDERER_CONFIGURATION}")
set(DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX "")
if (DX12_RENDERER_CONFIGURATION STREQUAL "Debug")
        set(DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX "d")
endif()
set(DX12_RENDERER_THIRD_PARTY_OUTPUTS
        "${DX12_RENDERER_THIRD_PARTY_OUTPUT_DIRECTORY}/NRI.lib"
        "${DX12_RENDERER_THIRD_PARTY_OUTPUT_DIRECTORY}/NRI.dll"
        "${DX12_RENDERER_THIRD_PARTY_OUTPUT_DIRECTORY}/NRD.lib"
        "${DX12_RENDERER_THIRD_PARTY_OUTPUT_DIRECTORY}/NRD.dll"
        "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/${DX12_RENDERER_CONFIGURATION}/meshoptimizer${DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX}.lib"
        "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/${DX12_RENDERER_CONFIGURATION}/assimp-vc143-mt${DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX}.lib"
        "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/lib/${DX12_RENDERER_CONFIGURATION}/DirectXTex${DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX}.lib"
        "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/lib/${DX12_RENDERER_CONFIGURATION}/DirectXMesh${DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX}.lib"
        "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/${DX12_RENDERER_CONFIGURATION}/Imath-3_2${DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX}.lib"
        "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/${DX12_RENDERER_CONFIGURATION}/OpenEXR-4_0${DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX}.lib"
        "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/${DX12_RENDERER_CONFIGURATION}/OpenEXRCore-4_0${DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX}.lib"
        "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/${DX12_RENDERER_CONFIGURATION}/Iex-4_0${DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX}.lib"
        "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/${DX12_RENDERER_CONFIGURATION}/IlmThread-4_0${DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX}.lib"
        "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/${DX12_RENDERER_CONFIGURATION}/zlibstatic${DX12_RENDERER_THIRD_PARTY_DEBUG_POSTFIX}.lib"
        )
set(DX12_RENDERER_THIRD_PARTY_STAMP "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/third_party_${DX12_RENDERER_CONFIGURATION}.stamp")
set(DX12_RENDERER_THIRD_PARTY_INPUTS
        "${DX12_RENDERER_SOURCE_ROOT}/CMakeIncludes/BuildThirdParty.cmake"
        "${DX12_RENDERER_SOURCE_ROOT}/CMakeIncludes/ThirdPartyBuild/CMakeLists.txt"
        "${DX12_RENDERER_SOURCE_ROOT}/CMakeIncludes/ThirdPartyDependencies.cmake"
        )
file(GLOB_RECURSE DX12_RENDERER_NRI_SOURCE_FILES LIST_DIRECTORIES FALSE "${DX12_RENDERER_SOURCE_ROOT}/External/NRI/*")
file(GLOB_RECURSE DX12_RENDERER_NRD_SOURCE_FILES LIST_DIRECTORIES FALSE "${DX12_RENDERER_SOURCE_ROOT}/External/NRD/*")
file(GLOB_RECURSE DX12_RENDERER_EXTERNAL_SOURCE_FILES LIST_DIRECTORIES FALSE
        "${DX12_RENDERER_SOURCE_ROOT}/External/meshoptimizer/*"
        "${DX12_RENDERER_SOURCE_ROOT}/External/assimp/*"
        "${DX12_RENDERER_SOURCE_ROOT}/External/DirectXTex/*"
        "${DX12_RENDERER_SOURCE_ROOT}/External/DirectXMesh/*"
        "${DX12_RENDERER_SOURCE_ROOT}/External/Imath/*"
        "${DX12_RENDERER_SOURCE_ROOT}/External/OpenEXR/*")
list(APPEND DX12_RENDERER_THIRD_PARTY_INPUTS
        ${DX12_RENDERER_NRI_SOURCE_FILES}
        ${DX12_RENDERER_NRD_SOURCE_FILES}
        ${DX12_RENDERER_EXTERNAL_SOURCE_FILES})

set(DX12_RENDERER_THIRD_PARTY_REBUILD_REQUIRED FALSE)
if (NOT EXISTS "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/CMakeCache.txt")
        set(DX12_RENDERER_THIRD_PARTY_REBUILD_REQUIRED TRUE)
endif()
if (NOT EXISTS "${DX12_RENDERER_THIRD_PARTY_STAMP}")
        set(DX12_RENDERER_THIRD_PARTY_REBUILD_REQUIRED TRUE)
endif()
foreach(DX12_RENDERER_THIRD_PARTY_OUTPUT IN LISTS DX12_RENDERER_THIRD_PARTY_OUTPUTS)
        if (NOT EXISTS "${DX12_RENDERER_THIRD_PARTY_OUTPUT}")
                set(DX12_RENDERER_THIRD_PARTY_REBUILD_REQUIRED TRUE)
                break()
        endif()
endforeach()
foreach(DX12_RENDERER_THIRD_PARTY_INPUT IN LISTS DX12_RENDERER_THIRD_PARTY_INPUTS)
        if ("${DX12_RENDERER_THIRD_PARTY_INPUT}" IS_NEWER_THAN "${DX12_RENDERER_THIRD_PARTY_STAMP}")
                set(DX12_RENDERER_THIRD_PARTY_REBUILD_REQUIRED TRUE)
                break()
        endif()
endforeach()

if (NOT DX12_RENDERER_THIRD_PARTY_REBUILD_REQUIRED)
        message(STATUS "NRI and NRD artifacts are up to date.")
        return()
endif()

set(DX12_RENDERER_THIRD_PARTY_CONFIGURE_COMMAND
        "${CMAKE_COMMAND}"
        -S "${DX12_RENDERER_SOURCE_ROOT}/CMakeIncludes/ThirdPartyBuild"
        -B "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}"
        -G "${DX12_RENDERER_GENERATOR}"
        "-DCMAKE_BUILD_TYPE=${DX12_RENDERER_CONFIGURATION}"
        "-DDX12_RENDERER_SOURCE_ROOT=${DX12_RENDERER_SOURCE_ROOT}"
        "-DDX12_RENDERER_DXC_EXECUTABLE=${DX12_RENDERER_DXC_EXECUTABLE}"
        )
if (DX12_RENDERER_GENERATOR_PLATFORM)
        list(APPEND DX12_RENDERER_THIRD_PARTY_CONFIGURE_COMMAND -A "${DX12_RENDERER_GENERATOR_PLATFORM}")
endif()
if (DX12_RENDERER_GENERATOR_TOOLSET)
        list(APPEND DX12_RENDERER_THIRD_PARTY_CONFIGURE_COMMAND -T "${DX12_RENDERER_GENERATOR_TOOLSET}")
endif()
# Forward only a usable external vcpkg toolchain. The optional wrapper belongs
# to the parent configure and must not poison this isolated cache with a stale
# vcpkg.cmake path from an older machine.
set(DX12_RENDERER_THIRD_PARTY_FORWARD_TOOLCHAIN "")
if (DX12_RENDERER_TOOLCHAIN_FILE AND EXISTS "${DX12_RENDERER_TOOLCHAIN_FILE}")
        get_filename_component(DX12_RENDERER_THIRD_PARTY_TOOLCHAIN_NAME
                "${DX12_RENDERER_TOOLCHAIN_FILE}" NAME)
        if (NOT DX12_RENDERER_THIRD_PARTY_TOOLCHAIN_NAME STREQUAL "OptionalVcpkgToolchain.cmake")
                set(DX12_RENDERER_THIRD_PARTY_FORWARD_TOOLCHAIN
                        "${DX12_RENDERER_TOOLCHAIN_FILE}")
        elseif (DEFINED ENV{VCPKG_ROOT} AND NOT "$ENV{VCPKG_ROOT}" STREQUAL "")
                file(TO_CMAKE_PATH "$ENV{VCPKG_ROOT}" DX12_RENDERER_ENV_VCPKG_ROOT)
                set(DX12_RENDERER_ENV_VCPKG_TOOLCHAIN
                        "${DX12_RENDERER_ENV_VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
                if (EXISTS "${DX12_RENDERER_ENV_VCPKG_TOOLCHAIN}")
                        set(DX12_RENDERER_THIRD_PARTY_FORWARD_TOOLCHAIN
                                "${DX12_RENDERER_ENV_VCPKG_TOOLCHAIN}")
                endif()
        endif()
endif()
if (DX12_RENDERER_THIRD_PARTY_FORWARD_TOOLCHAIN)
        list(APPEND DX12_RENDERER_THIRD_PARTY_CONFIGURE_COMMAND
                "-DCMAKE_TOOLCHAIN_FILE=${DX12_RENDERER_THIRD_PARTY_FORWARD_TOOLCHAIN}")
endif()

message(STATUS "Building isolated NRI and NRD dependencies")
execute_process(COMMAND ${DX12_RENDERER_THIRD_PARTY_CONFIGURE_COMMAND} RESULT_VARIABLE DX12_RENDERER_THIRD_PARTY_CONFIGURE_RESULT)
if (NOT DX12_RENDERER_THIRD_PARTY_CONFIGURE_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to configure isolated NRI and NRD dependencies.")
endif()

execute_process(
        COMMAND "${CMAKE_COMMAND}" --build "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}" --config "${DX12_RENDERER_CONFIGURATION}" --target DX12RendererNRI
        RESULT_VARIABLE DX12_RENDERER_NRI_BUILD_RESULT)
if (NOT DX12_RENDERER_NRI_BUILD_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to build isolated NRI dependency.")
endif()

execute_process(
        COMMAND "${CMAKE_COMMAND}" --build "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}" --config "${DX12_RENDERER_CONFIGURATION}" --target DX12RendererNRD
        RESULT_VARIABLE DX12_RENDERER_NRD_BUILD_RESULT)
if (NOT DX12_RENDERER_NRD_BUILD_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to build isolated NRD dependency.")
endif()

execute_process(
        COMMAND "${CMAKE_COMMAND}" --build "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}" --config "${DX12_RENDERER_CONFIGURATION}" --target DX12RendererExternal
        RESULT_VARIABLE DX12_RENDERER_EXTERNAL_BUILD_RESULT)
if (NOT DX12_RENDERER_EXTERNAL_BUILD_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to build isolated vendored dependencies.")
endif()
file(TOUCH "${DX12_RENDERER_THIRD_PARTY_STAMP}")
