set(DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY "${CMAKE_BINARY_DIR}/ThirdParty")
set(DX12_RENDERER_NRD_SHADER_INCLUDE_DIRECTORY "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/NRD/Shaders")
set(DX12_RENDERER_OIDN_SOURCE_DIRECTORY "${CMAKE_SOURCE_DIR}/External/OIDN")
set(DX12_RENDERER_OIDN_BUILD_DIRECTORY "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/OIDN")
set(DX12_RENDERER_OIDN_GENERATED_INCLUDE_DIRECTORY "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/include/OpenImageDenoise")
set(DX12_RENDERER_OIDN_TBB_ROOT "C:/vcpkg/installed/x64-windows" CACHE PATH "oneTBB installation root used by the isolated OIDN build.")
set(DX12_RENDERER_OIDN_TBB_CONFIG_DIRECTORY "${DX12_RENDERER_OIDN_TBB_ROOT}/share/tbb" CACHE PATH "oneTBB CMake package directory used by the isolated OIDN build.")
set(DX12_RENDERER_OIDN_TBB_RUNTIME_ROOT "C:/vcpkg/installed/x64-windows" CACHE PATH "oneTBB runtime root deployed with OIDN.")
set(DX12_RENDERER_OIDN_ISPC_EXECUTABLE "${CMAKE_BINARY_DIR}/ThirdPartyTools/ispc-v1.30.0-windows/bin/ispc.exe" CACHE FILEPATH "ISPC executable used by the isolated OIDN build.")
file(MAKE_DIRECTORY "${DX12_RENDERER_OIDN_GENERATED_INCLUDE_DIRECTORY}")

function(dx12_renderer_define_imported_library target_name include_directory)
        add_library(${target_name} SHARED IMPORTED GLOBAL)
        set_target_properties(${target_name} PROPERTIES
                IMPORTED_CONFIGURATIONS "Debug;Release"
                IMPORTED_IMPLIB_DEBUG "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/Debug/${target_name}.lib"
                IMPORTED_LOCATION_DEBUG "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/Debug/${target_name}.dll"
                IMPORTED_IMPLIB_RELEASE "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/Release/${target_name}.lib"
                IMPORTED_LOCATION_RELEASE "${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}/bin/Release/${target_name}.dll"
                INTERFACE_INCLUDE_DIRECTORIES "${include_directory}"
                )
endfunction()

dx12_renderer_define_imported_library(NRI "${CMAKE_SOURCE_DIR}/External/NRI/Include")
dx12_renderer_define_imported_library(NRD "${CMAKE_SOURCE_DIR}/External/NRD/Include")
set_target_properties(NRI PROPERTIES INTERFACE_COMPILE_DEFINITIONS "NRI_STATIC_LIBRARY=0")
set_target_properties(NRD PROPERTIES INTERFACE_COMPILE_DEFINITIONS "NRD_STATIC_LIBRARY=0")

add_library(OIDN SHARED IMPORTED GLOBAL)
set_target_properties(OIDN PROPERTIES
        IMPORTED_CONFIGURATIONS "Debug;Release"
        IMPORTED_IMPLIB_DEBUG "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/Debug/OpenImageDenoise.lib"
        IMPORTED_LOCATION_DEBUG "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/Debug/OpenImageDenoise.dll"
        IMPORTED_IMPLIB_RELEASE "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/Release/OpenImageDenoise.lib"
        IMPORTED_LOCATION_RELEASE "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/Release/OpenImageDenoise.dll"
        INTERFACE_INCLUDE_DIRECTORIES "${DX12_RENDERER_OIDN_SOURCE_DIRECTORY}/include;${DX12_RENDERER_OIDN_GENERATED_INCLUDE_DIRECTORY}"
        )
set(DX12_RENDERER_OIDN_RUNTIME_FILES
        "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/$<CONFIG>/OpenImageDenoise.dll"
        "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/$<CONFIG>/OpenImageDenoise_core.dll"
        "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/$<CONFIG>/OpenImageDenoise_device_cpu.dll"
        "${DX12_RENDERER_OIDN_BUILD_DIRECTORY}/$<CONFIG>/OpenImageDenoise_device_cuda.dll"
        "${DX12_RENDERER_OIDN_TBB_RUNTIME_ROOT}/bin/tbb12.dll"
        )

add_library(NRDIntegration INTERFACE IMPORTED GLOBAL)
set_target_properties(NRDIntegration PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_SOURCE_DIR}/External/NRD/Integration"
        )

function(dx12_renderer_add_third_party_prebuild target_name)
        # Keep the third-party refresh private to its consuming target. A custom
        # target would otherwise materialize as a developer-visible VS project.
        add_custom_command(TARGET ${target_name} PRE_BUILD
                COMMAND "${CMAKE_COMMAND}" "-DDX12_RENDERER_SOURCE_ROOT=${CMAKE_SOURCE_DIR}" "-DDX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY=${DX12_RENDERER_THIRD_PARTY_BUILD_DIRECTORY}" "-DDX12_RENDERER_CONFIGURATION=$<CONFIG>" "-DDX12_RENDERER_GENERATOR=${CMAKE_GENERATOR}" "-DDX12_RENDERER_GENERATOR_PLATFORM=${CMAKE_GENERATOR_PLATFORM}" "-DDX12_RENDERER_GENERATOR_TOOLSET=${CMAKE_GENERATOR_TOOLSET}" "-DDX12_RENDERER_DXC_EXECUTABLE=${DX12_RENDERER_DXC_EXECUTABLE}" "-DDX12_RENDERER_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}" -P "${CMAKE_SOURCE_DIR}/CMakeIncludes/BuildThirdParty.cmake"
                COMMENT "Updating isolated NRI and NRD dependencies"
                VERBATIM)
endfunction()

function(dx12_renderer_add_oidn_prebuild target_name)
        add_custom_command(TARGET ${target_name} PRE_BUILD
                COMMAND "${CMAKE_COMMAND}" "-DDX12_RENDERER_SOURCE_ROOT=${CMAKE_SOURCE_DIR}" "-DDX12_RENDERER_OIDN_BUILD_DIRECTORY=${DX12_RENDERER_OIDN_BUILD_DIRECTORY}" "-DDX12_RENDERER_CONFIGURATION=$<CONFIG>" "-DDX12_RENDERER_GENERATOR=${CMAKE_GENERATOR}" "-DDX12_RENDERER_GENERATOR_PLATFORM=${CMAKE_GENERATOR_PLATFORM}" "-DDX12_RENDERER_GENERATOR_TOOLSET=${CMAKE_GENERATOR_TOOLSET}" "-DDX12_RENDERER_OIDN_TBB_ROOT=${DX12_RENDERER_OIDN_TBB_ROOT}" "-DDX12_RENDERER_OIDN_TBB_CONFIG_DIRECTORY=${DX12_RENDERER_OIDN_TBB_CONFIG_DIRECTORY}" "-DDX12_RENDERER_OIDN_ISPC_EXECUTABLE=${DX12_RENDERER_OIDN_ISPC_EXECUTABLE}" "-DDX12_RENDERER_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}" -P "${CMAKE_SOURCE_DIR}/CMakeIncludes/BuildOidn.cmake"
                COMMENT "Updating isolated Open Image Denoise CPU and CUDA dependencies"
                VERBATIM)
endfunction()
